language: node_js
node_js:
  - 'lts/*'


matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode9.4
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services:
        - xvfb

cache:
  directories:
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run cucumber; fi
  - npm test
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm run release:linux;
    else
      npm run release:osx
    fi
